// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import '@hotwired/turbo-rails';
import 'controllers';
import 'jquery';
import 'bootstrap';
import 'custom/menu';
import 'custom/courses_subjects';
import 'custom/add_members_modal';
import 'custom/trainee/subject_details';
import 'custom/document_upload';
import 'custom/supervisor/users';
import 'custom/admin/users';
import 'custom/add_subject_in_category';
import 'custom/add_subject_in_course';
import 'custom/supervisor/tasks_form';
import 'custom/admin/new_supervisor';
import 'custom/course_edit';
import 'custom/subject_search';
import 'custom/admin/subjects';
